Search users
movnet-capstone/backend pull request #17
Opened 2019-03-14 01:44 UTC by Stuart-Wilcox

- search for users based on username -> looks for matching query in username. ie `query='wil'` will catch the username `'swilcox7'`
- ex `http://localhost:8080/api/user/search?query=swilcox7`
- updated swagger docs to reflect the change

2019-03-14 06:24 UTC, AgostonSzepessy submitted a review, later dismissed

2019-03-14 06:24 UTC, AgostonSzepessy commented on src/models/user.ts
> +      return await knex('User').select('fname', 'username').where('username', 'like', `%${username}%`);
We should return `lname` as well

2019-03-17 19:36 UTC, Stuart-Wilcox commented on src/models/user.ts
> +      return await knex('User').select('fname', 'username').where('username', 'like', `%${username}%`);
Latest commit has the requested changes

2019-03-17 23:49 UTC, AgostonSzepessy requested changes

2019-03-17 23:49 UTC, AgostonSzepessy commented on swagger.json
> +                "fname": { "type": "string" }
We should add `lname` here too

2019-03-18 18:44 UTC, AgostonSzepessy approved these changes
LGTM

2019-03-18 18:44 UTC, merged